### PR TITLE
multiplication and division class with tests

### PR DESCRIPTION
**Pull request by Priyam-Swine**
multiplication and division

### CODE REVIEW

**Review by eps0003 — CHANGES_REQUESTED** [review]
You forgot to register the two new operators in the calculator constructor.

**Comment by Priyam-Swine** [comment]
changes made

**Review by eps0003 — CHANGES_REQUESTED** [review]
A unit test for dividing by zero is needed.

**Comment by Priyam-Swine** [comment]
Added the required tests

**Review by eps0003 — APPROVED** [review]
Looks good now. Thanks.

**Pull request merged**
